### ISSUE TITLE
ValueError: not enough values to unpack (expected 3, got 2)

### ISSUE THREAD

**Issue by ali97hz** [MicrocontrollersAndMore/OpenCV_3_License_Plate_Recognition_Python#14]
hello 

I just run it and get this error 
I saw somebody else got the same error 

DetectPlates.py", line 133, in findPossibleCharsInScene
    imgContours, contours, npaHierarchy = cv2.findContours(imgThreshCopy, cv2.RETR_LIST, cv2.CHAIN_APPROX_SIMPLE)   # find all contours
ValueError: not enough values to unpack (expected 3, got 2)

can anybody help me with this?

**Comment by Sgtulam** [comment]
the function cv2.findContours() has been changed to return only the contours and the hierarchy and not ret

you should change it to:

contours,hierachy=cv2.findContours(thresh,cv2.RETR_TREE,cv2.CHAIN_APPROX_SIMPLE)
